name: httprate
description: Rate limit and exponetial backoff for mainly http request.
version: 0.1.0
author: Ole Martin Gjersvik <olem@olem.org>
homepage: https://github.com/gjersvik/httprate

environment:
  sdk: '>=1.9.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
