name: httprate
description: Rate limit and exponetial backoff for mainly http request.
version: 0.2.0
author: Ole Martin Gjersvik <olem@olem.org>
homepage: https://github.com/gjersvik/httprate

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  http: "^0.11.3"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
